baseURL: https://squalr.us/
title: Chad Schulz
theme: m10c
copyright: "Â©2021 Chad Schulz"
paginate: 10

languageCode: en-us
enableRobotsTXT: true

googleAnalytics: UA-10469485-9

permalinks:
  blog: /:year/:month/:title/

params:
  author: 'Chad Schulz'
  description: "Senior SDE Manager at Microsoft. Currently working on azure.com."
  avatar: "/img/bio.jpg"
  menu_item_separator: "-"
  favicon: "/img/favicon.ico"
  images:
  - img/bio.jpg
  style:
    darkestColor: "#242930"
    darkColor: "#353b43"
    lightColor: "#afbac4"
    lightestColor: "#ffffff"
    primaryColor: "#52F0E0"

  dateFormat: "Monday, January 2, 2006"

  social:
  - icon: "github"
    url: "https://github.com/squalrus"
  - icon: "twitter"
    url: "https://twitter.com/chadschulz"
  - icon: "linkedin"
    url: "https://www.linkedin.com/in/chadschulz/"

menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 10
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 20
    - identifier: "chillout"
      name: "Chillout"
      url: "/chillout-with-chad/"
      weight: 30
